version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9032:9032"
    environment:
      - NODE_ENV=production
      - PORT=9032
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9032/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 